server:
  port: ${port:9000}

spring:
  application:
    name: demo
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    platform: mysql
    url: jdbc:mysql://dungiapp.ctezwyeyfqua.ap-northeast-2.rds.amazonaws.com/wow?autoReconnect=true
    username: dungiapp
    password: dungiapp
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    static-path-pattern: /static/**
    static-locations: file:/resources/static
    add-mappings: true

  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

